# Template workflow (Azure Pipelines)
# Build and test a project in all available setup configurations configured in DARMA-taking/workflows
# See also: github version at .github/workflows/build-and-test.yml

# WIP. Workflows pipeline with matrix
# ***: TODO only once this workflow file works and is completed
name: PR tests (Template)

trigger:
  branches:
    include:
      - master

pr:
  drafts: true # TODO: set to false***
  autoCancel: true
  branches:
    include:
      - '*'

variables:
  CI_REPO: DARMA-tasking/workflows
  CI_BRANCH: 2-implement-common-docker-containers # TODO: set back to master***

jobs:
- job: getMatrix
  pool:
    vmImage: 'ubuntu-latest'
  displayName: 'Retrieve Setup matrix'
  steps:
  - bash: |
      wget https://raw.githubusercontent.com/${{ variables.CI_REPO }}/refs/heads/${{ variables.CI_BRANCH }}/ci/shared/matrix/azure.json
      matrix=$(cat azure.json | jq -c '.matrix')
      echo "##vso[task.setvariable variable=matrix;isOutput=true]$matrix"
    displayName: 'Retrieve Setup matrix'
    name: getMatrixStep

- job: run
  dependsOn: getMatrix
  strategy:
    matrix: $[ dependencies.getMatrix.outputs['getMatrixStep.matrix'] ]
  displayName: PR tests / # contrary to github cannot get a way to inject label from matrix. azure just appends the item key automatically
  pool:
    vmImage: $(vmImage)
  steps:
  - bash: |
      echo "Environment=$(label)"
      echo "Runner=$(vmImage)"
      if [ "$(image)" != "" ]
      then
        echo "> With Docker Image=$(image)"
      else
        echo "> With Runner Setup=$(setup)"
      fi
    displayName: Display configuration

  # TODO: add missing steps as in .github/workflows/build-and-test.yml
