# Azure Pipelines Worflow
# Note: github version of this workflow is at .github/workflows/build-and-test.yml
# WIP. Workflows pipeline with matrix
# ***: TODO only once this workflow file works and is completed
name: Build and test (Template)

trigger:
  branches:
    include:
      - 2-implement-common-docker-containers # TODO: set back to master and develop***

pr:
  drafts: true # TODO: set to false***
  autoCancel: true
  branches:
    include:
      - '*'

variables:
  CI_REPO: DARMA-tasking/workflows
  CI_BRANCH: 2-implement-common-docker-containers # TODO: set back to master***

jobs:
- job: getMatrix
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: |
      wget https://raw.githubusercontent.com/${{ variables.CI_REPO }}/refs/heads/${{ variables.CI_BRANCH }}/ci/shared/matrix/azure.json
      matrix=$(cat azure.json | jq -c '.matrix')
      echo "##vso[task.setvariable variable=matrix;isOutput=true]$matrix"
    displayName: 'Retrieve Setup matrix'
    name: getMatrixStep

- job: setup
  dependsOn: getMatrix
  strategy:
    matrix: $[ dependencies.getMatrix.outputs['getMatrixStep.matrix'] ]
  pool:
    vmImage: $(vmImage)
  steps:
  - bash: echo 'Hello !'      
    displayName: 'Setup dependencies'