#!/usr/bin/env bash

# This file has been generated by a script. Do not edit.

echo "Installing dependencies..."

CURRENT_DIR="$(dirname -- "$(realpath -- "$0")")"

pushd $CURRENT_DIR

./deps/packages.sh "ca-certificates" "less" "curl" "jq" "git" "wget" "zlib1g" "zlib1g-dev" "ninja-build" "valgrind" "make-guile" "libomp5" "libunwind-dev" "ccache" "gcc-14" "g++-14"
./deps/cmake.sh "3.23.4"
./deps/openmpi.sh "v5.0" "5.0.4" "-j4"

popd