#!/usr/bin/env bash

#
# Ubuntu 22.04 / gcc-11 / Python[3.8-3.12] / MPI 5.0.4 / VTK 9.3.1 - Installation
# Note: requires
# - `git` and `wget` installed.
# - run as root

#
# IMPORTANT: This file has been generated by a script. Please do not edit !
#

SCRIPTS_INSTALL_DIR=/opt/scripts/ci
# TODO: change 2-implement-common-docker-containers to master once scripts when PR is ready
SCRIPTS_DEPS_URL="https://raw.githubusercontent.com/DARMA-tasking/workflows/refs/heads/2-implement-common-docker-containers/ci/shared/scripts/deps"

mkdir -p $SCRIPTS_INSTALL_DIR

# Dependencies
mkdir -p $SCRIPTS_INSTALL_DIR/deps
# > Retrieve .sh scripts
pushd $SCRIPTS_INSTALL_DIR/deps
wget $SCRIPTS_DEPS_URL/packages.sh
wget $SCRIPTS_DEPS_URL/cmake.sh
wget $SCRIPTS_DEPS_URL/conda.sh
wget $SCRIPTS_DEPS_URL/conda-python-env.sh
wget $SCRIPTS_DEPS_URL/vtk.sh
wget $SCRIPTS_DEPS_URL/openmpi.sh

# > Run install instructions
chmod u+x *.sh
ls -l
./packages.sh "ca-certificates" "curl" "git" "jq" "less" "libomp5" "libunwind-dev make-guile" "ninja-build" "valgrind" "wget" "zlib1g" "zlib1g-dev" "ccache" "gcc-11" "g++-11"
./cmake.sh "3.23.4"
./conda.sh 
./conda-python-env.sh "3.8" "nanobind yaml setuptools"
./conda-python-env.sh "3.9" "nanobind yaml setuptools"
./conda-python-env.sh "3.10" "nanobind yaml setuptools"
./conda-python-env.sh "3.11" "nanobind yaml setuptools"
./conda-python-env.sh "3.12" "nanobind yaml setuptools"
./vtk.sh "9.3.1"
./openmpi.sh "v5.0" "5.0.4"

popd # $SCRIPTS_INSTALL_DIR/deps

echo "Cleaning..."
rm -rf $SCRIPTS_INSTALL_DIR
