#!/usr/bin/env bash

# CI environment setup script
# Ubuntu 22.04 / gcc-11 / Python[3.8-3.12] / MPI 5.0.4 / VTK 9.3.1

#
# IMPORTANT: This file has been generated by a script. Please do not edit !
#

SCRIPTS_REPO=DARMA-tasking/workflows
SCRIPTS_REPO_BRANCH=2-implement-common-docker-containers
SCRIPTS_DEP_REGEX="ci/shared/scripts/deps/.*\.sh"
SCRIPTS_INSTALL_DIR=/opt/scripts/ci

mkdir -p $SCRIPTS_INSTALL_DIR
chown -R $(whoami) $SCRIPTS_INSTALL_DIR

# List scripts in `ci/shared/scripts/deps` from the scripts repository
mkdir -p ~/tmp
pushd ~/tmp
git clone -b 2-implement-common-docker-containers --no-checkout --depth 1 https://github.com/$SCRIPTS_REPO workflows
ls -l
pushd workflows
arr=($(git ls-tree -r --name-only refs/heads/$SCRIPTS_REPO_BRANCH | grep -E "$SCRIPTS_DEP_REGEX"))
popd # ~/tmp/workflows
popd # ~/tmp
rm -rf ~/tmp

# Retrieve scripts from remote & run setup instructions
mkdir -p $SCRIPTS_INSTALL_DIR/deps
pushd $SCRIPTS_INSTALL_DIR/deps
for script_name in ${arr[@]}
do
    wget https://raw.githubusercontent.com/$SCRIPTS_REPO/refs/heads/$SCRIPTS_REPO_BRANCH/$script_name
done
# Install dependencies
chmod u+x *.sh
ls -l
./packages.sh "ca-certificates" "curl" "git" "jq" "less" "libomp5" "libunwind-dev make-guile" "ninja-build" "valgrind" "wget" "zlib1g" "zlib1g-dev" "ccache" "gcc-11" "g++-11"
./cmake.sh "3.23.4"
./conda.sh 
./conda-python-env.sh "3.8" "nanobind yaml setuptools"
./conda-python-env.sh "3.9" "nanobind yaml setuptools"
./conda-python-env.sh "3.10" "nanobind yaml setuptools"
./conda-python-env.sh "3.11" "nanobind yaml setuptools"
./conda-python-env.sh "3.12" "nanobind yaml setuptools"
./vtk.sh "9.3.1"
./openmpi.sh "v5.0" "5.0.4"
popd # $SCRIPTS_INSTALL_DIR/deps

echo "Cleaning..."
rm -rf $SCRIPTS_INSTALL_DIR
