#!/usr/bin/env bash

# This file has been generated by a script. Do not edit.

echo "Installing dependencies..."

CURRENT_DIR="$(dirname -- "$(realpath -- "$0")")"

pushd $CURRENT_DIR

./deps/packages.sh "ca-certificates" "less" "curl" "jq" "git" "wget" "zlib1g" "zlib1g-dev" "ninja-build" "valgrind" "make-guile" "libomp5" "libunwind-dev" "ccache" "gcc-11" "g++-11"
./deps/cmake.sh "3.23.4"
./deps/conda.sh 
./deps/conda-python-env.sh "3.8" "nanobind yaml setuptools"
./deps/conda-python-env.sh "3.9" "nanobind yaml setuptools"
./deps/conda-python-env.sh "3.10" "nanobind yaml setuptools"
./deps/conda-python-env.sh "3.11" "nanobind yaml setuptools"
./deps/conda-python-env.sh "3.12" "nanobind yaml setuptools"
./deps/vtk.sh "9.3.1"
./deps/openmpi.sh "v5.0" "5.0.4"

popd