#!/usr/bin/env python

import copy
import os
import sys

from util import resolve_conf
import yaml

class DockerBuilder:
    """Dockerfile generator class"""

    def build(self, args: list):
        """Build an image using a given docker configuration fro the config file"""

        raw_config: dict = {}
        with open(os.path.dirname(__file__) + '/config.yaml', 'r', encoding="utf-8") as file:
            raw_config = yaml.safe_load(file)

        config = resolve_conf(copy.deepcopy(raw_config))
        images = config.get("images")
        environments = config.get("environments")

        if len(args) > 0:
            image_key = args[0]
            if not image_key in images.keys():
                print(f"[error] Invalid image name {image_key}.\nAllowed: "
                                f"{', '. join(images.keys())}")
                raise SystemExit(1)
        else:
            # Step 1: list platforms and their configurations
            choices = {k: v for k, v in enumerate(images.keys())}
            print("Choose image: ")
            for i in choices:
                image = images.get(choices[i])
                environment = environments.get(image.get('environment'))
                lbl = environment.get('label')
                print(
                    f"\033[1m[{i}] {choices[i]}\033[0m\n"
                    f"    \033[3;34m{lbl}\033[0m"
                )
            choice = input("> ")

            image_key = choices[int(choice)]

        image = images.get(image_key)
        print("Selected image:")
        print("---------------------------")
        print(yaml.dump(image, default_flow_style=True))
        print("---------------------------")

        repo = image.get("repository")
        tag = image_key
        environment = environments.get(image.get('environment'))
        deps = environment.get("deps", {})

        # Add compiler packages
        compiler = environment.get('compiler')
        args = {
            # General
            "ARCH": image.get('arch'),
            "BASE": image.get('base'),
            "ENVIRONMENT_ID": image.get('environment'),
            # Compiler
            "CC": compiler.get('cc', '') if compiler is not None else '',
            "CXX": compiler.get('cxx', '') if compiler is not None else '',
            "FC": compiler.get('fc', '') if compiler is not None else '',
            "GCOV": compiler.get('gcov', '') if compiler is not None else ''
        }

        space = ' '
        cmd = ("docker build"
                f" --tag {repo}:{tag}"             
                f" --file {os.path.dirname(__file__)}/docker/base.dockerfile ."
                f" {space.join([f'--build-arg {k}={v}' for (k,v) in args.items()])}"  
                " --progress=plain"
                " --no-cache"
            )
        print(cmd)
        os.system(cmd)

        # TODO: option to push to Dockerhub

DockerBuilder().build(sys.argv[1:])
