#!/usr/bin/env python

import copy
import os
import json

from util import resolve_conf
import yaml

AZURE_PIPELINES_OUTPUT_DIR="ci/azure"
GITHUB_PIPELINES_OUTPUT_DIR=".github/workflows"

class MatrixGenerator:
    """MatrixGenerator class for CI pipelines"""

    def generate(self):
        """Generate a matrix of runners and inner environments to be used by CI pipelines"""

        raw_config: dict = {}
        with open(os.path.dirname(__file__) + '/config.yaml', 'r', encoding="utf-8") as file:
            raw_config = yaml.safe_load(file)
        config = resolve_conf(copy.deepcopy(raw_config))

        image_tags = dict((k, v.get("repository") + ":" + k)
                           for k, v in config.get("images").items())

        for runner_type in ["github", "azure-pipelines"]:
            runners = dict((k, v) for k, v in config.get("runners").items() if v.get("type") == runner_type)

            matrix = []
            for (runner_id, runner) in runners.items():
                setup = {}
                setup_in = runner.get("setup-in")
                if setup_in == "docker":
                    image = config.get("images").get(runner.get("image"))
                    if image is None:
                        raise RuntimeError(f"Image not found {runner.get('image')}")
                    setup_id = image.get("setup")
                elif setup_in == "runner" or setup_in is None:
                    setup_id = runner.get("setup")
                else:
                    raise ValueError(f"Invalid option {setup_id} for key `setup-in`."
                                       "Supported values are docker|runner (runner if unset)")
                setup = config.get("setup").get(setup_id)
                if setup is None:
                    raise ValueError(f"Environment {setup_id} not found")
                matrix.append({
                    "runs-on": runner.get("runs-on"),
                    "id": runner_id,
                    "label": setup.get("label", setup_id),
                    "image": image_tags.get(runner.get("image", None), None),
                    "setup": setup_id,
                    "setup-in": setup_in
                })

            data = json.dumps({
                "_comment": "This file has been generated. Please do not edit",
                "matrix": matrix}, indent=2)
            with open(os.path.dirname(__file__) + f"/shared/workflows/{runner_type}-matrix.json", 'w+',
                        encoding="utf-8") as file:
                file.write(data)

MatrixGenerator().generate()
