#!/usr/bin/env python

import copy
import os
import sys

from util import resolve_conf
import yaml

class DockerBuilder:
    """Dockerfile generator class"""

    def build(self, args: list):
        """Build an image using a given docker configuration fro the config file"""

        raw_config: dict = {}
        with open(os.path.dirname(__file__) + '/config.yaml', 'r', encoding="utf-8") as file:
            raw_config = yaml.safe_load(file)

        config = resolve_conf(copy.deepcopy(raw_config))
        images = config.get("images")
        setup = config.get("setup")

        image = None
        if len(args) > 0:
            image_name = args[0]

            images_by_name = dict((v.get("repository") + ":" + v.get("tag", k), k)
                           for k, v in config.get("images").items())
            image_key = images_by_name.get(image_name)
            if image_key is None:
                print(f"[error] Invalid image {image_name}.\nAvailable images:{(os.linesep + '- ')}"
                                f"{(os.linesep + '- ') . join(images_by_name.keys())}")
                raise SystemExit(1)
        else:
            # Step 1: list platforms and their configurations
            choices = {k: v for k, v in enumerate(images.keys())}
            print("Choose image: ")
            for i in choices:
                image = images.get(choices[i])
                setup_id = image.get('setup')
                current_setup = setup.get(setup_id)
                if current_setup is None:
                    raise RuntimeError(f"Invalid setup {setup_id}")
                lbl = current_setup.get('label', image.get('setup'))
                print(
                    f"\033[1m[{i}] {choices[i]}\033[0m\n"
                    f"    \033[3;34m{lbl}\033[0m"
                )
            choice = input("> ")

            image_key = choices[int(choice)]

        image = images.get(image_key)
        print("Selected image:")
        print("---------------------------")
        print(yaml.dump(image, default_flow_style=True))
        print("---------------------------")

        repo = image.get("repository")
        tag = image_key
        image_setup = setup.get(image.get('setup'))

        # Add compiler packages
        compiler = image_setup.get('compiler')
        args = {
            # General
            "ARCH": image.get('arch'),
            "BASE": image.get('base'),
            "SETUP_ID": image.get('setup'),
            # Compiler (C, C++, Fortran, coverage tool)
            "CC": compiler.get('cc', '') if compiler is not None else '',
            "CXX": compiler.get('cxx', '') if compiler is not None else '',
            "FC": compiler.get('fc', '') if compiler is not None else '',
            "GCOV": compiler.get('gcov', '') if compiler is not None else ''
        }

        space = ' '
        cmd = ("docker build . "
                f" --tag {repo}:{tag}"             
                f" --file {os.path.dirname(__file__)}/docker/base.dockerfile"
                f" {space.join([f'--build-arg {k}={v}' for (k,v) in args.items()])}"  
                " --progress=plain"
                " --no-cache"
            )
        print(cmd)
        os.system(cmd)

        # TODO: option to push to Dockerhub

DockerBuilder().build(sys.argv[1:])
