# Configuration of the desired CI target platforms
# This way to separate environment definitions and runner definitions open the possibility run an environment on different runners
# 
# This file defines all the configurations to test in CI
# NOTE: This is an investigation about a more complex but more scalable way to difine th platforms to target in CI.
# This file might be used as an input to scripts to
# - generate dockerfile environment files (for nodes with type='docker-image') and being able to build and push images
# - generate Github workflows yaml files stub (for nodes with type='github-runner')*
# - generate Azure pipelines yaml files stub (for nodes with type='azure-runner')*
# *In VT we have some specific stuff. We might want to add some compose logic with some generated pipeline stub and complementary
# project-specific pipeline

# THIS IS A LOT OF WORK BUT MIGHT BE VERY USEFUL

defaults:
  apt_packages: [ca-certificates, curl, git, jq, less, libomp5, libunwind-dev make-guile,
      ninja-build, valgrind, wget, zlib1g, zlib1g-dev, ccache, python3]
  brew_packages: [ coreutils ]
  repo: lifflander1/vt

compilers:
  gcc-9: { type: gnu, cc: gcc-9, cxx: g++-9, fc: gfortran, gcov: gcov }
  gcc-11: { type: gnu, cc: gcc-11, cxx: g++-11, fc: gfortran, gcov: gcov }
  gcc-12: { type: gnu, cc: gcc-12, cxx: g++-12, fc: gfortran, gcov: gcov }

setup:
  ubuntu-20.04-gcc-9-12.2.0-cpp:
    label: gcc-9, ubuntu, mpich, zoltan
    compiler: "@compilers.gcc-9"
    deps:
      packages: "@defaults.apt_packages"
      cmake: ['3.23.4']
      vtk: [ '9.3.1' ]
      openmpi: ['v5.0', '5.0.4']
      zoltan: [-j4', '/trilinos-install']

images:
  amd64-ubuntu-20.04-gcc-9-12.2.0-cpp:
    repository: "@defaults.repo"
    tag: amd64-ubuntu-20.04-gcc-9-12.2.0-cpp
    dockerfile: ubuntu-cpp-base.dockerfile
    arch: amd64
    base: ubuntu:20.04
    setup: ubuntu-20.04-gcc-9-12.2.0-cpp

runners:
  amd64-ubuntu-20.04-gcc-9-12.2.0-cpp:
    type: github
    runs-on: ubuntu-20.04
    setup-in: docker
    image: amd64-ubuntu-20.04-gcc-9-12.2.0-cpp
