#!/usr/bin/env bash

# This file has been generated by a script. Please do not edit !

echo "Installing dependencies..."

CURRENT_DIR="$(dirname -- "$(realpath -- "$0")")"

pushd $CURRENT_DIR

%INSTRUCTIONS%

popd