name: DARMA repositories check

on:
  # schedule: 
  #   - cron: '*/30 * * * *'
  push:
    branches:
    - 1-validate-required-workflows-usage-across-repositories

jobs:
  list_repositories:
    name: List repositories
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
  
      - name: List repositories
        id: list-repositories
        run: |
          REPOSITORIES=$(bash ci/list_repositories.sh)
          echo "repositories=$(echo $REPOSITORIES)" >> $GITHUB_OUTPUT
    outputs:
      repositories: ${{ steps.list-repositories.outputs.repositories }}

  check_repository:
    name: Check repository (${{ matrix.repository.name }})
    runs-on: ubuntu-latest
    needs: list_repositories
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        repository: ${{ fromJson(needs.list_repositories.outputs.repositories ) }}
    steps:
      - uses: actions/checkout@v4

      - name: Check repositories
        run: |
          bash ./ci/check_repository.sh ${{ matrix.repository.name }}

          